# Auto-label configuration for actions/labeler
# Maps file path patterns to PR labels
# This is a GENERIC config — repos can override with their own .github/labeler.yml

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
          - 'README*'
          - 'CHANGELOG*'

# CI/CD changes
ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '*.yml'
          - '*.yaml'
          - 'Makefile'

# Infrastructure / Terraform
terraform:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.tf'
          - '**/*.tfvars'
          - '**/.terraform.lock.hcl'

# Docker changes
docker:
  - changed-files:
      - any-glob-to-any-file:
          - '**/Dockerfile*'
          - '**/docker-compose*.yml'
          - '**/.dockerignore'

# Python changes
python:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.py'
          - 'requirements*.txt'
          - 'pyproject.toml'
          - 'setup.py'
          - 'setup.cfg'

# TypeScript / JavaScript changes
typescript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.js'
          - '**/*.jsx'
          - 'package.json'
          - 'tsconfig*.json'

# Shell scripts
shell:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.sh'
          - '**/*.bash'

# Configuration files
config:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.json'
          - '**/*.toml'
          - '**/*.ini'
          - '**/*.cfg'
          - '.editorconfig'
          - '.gitignore'
