"""Core models, interfaces, and exceptions."""
from src.core.exceptions import (
    AssetNotFoundError,
    ConfigurationError,
    FFmpegError,
    ImageGenerationError,
    LLMContentFilterError,
    LLMError,
    LLMRateLimitError,
    MusicGenerationError,
    PipelineError,
    ScriptValidationError,
    ThumbnailError,
    TTSError,
    TTSQuotaExceededError,
    VideoCompositionError,
    VideoGenerationError,
    YouTubeAPIError,
    YouTubeAuthError,
    YouTubeAutomationError,
    YouTubeQuotaExceededError,
    YouTubeUploadError,
    YTAutoError,
)
from src.core.interfaces import (
    ContentPipeline,
    ImageGenerator,
    ScriptGenerator,
    ThumbnailGenerator,
    TTSEngine,
    VideoComposer,
    VideoGenerator,
    YouTubeUploader,
)
from src.core.models import (
    CHANNEL_CONFIGS,
    AudioSegment,
    ChannelConfig,
    ChannelType,
    ContentStatus,
    Script,
    Thumbnail,
    VideoProject,
    VideoStyle,
    VisualAsset,
)
from src.core.orchestrator import Orchestrator

__all__ = [
    # Exceptions
    "YTAutoError",
    "YouTubeAutomationError",
    "ConfigurationError",
    "PipelineError",
    "LLMError",
    "LLMRateLimitError",
    "LLMContentFilterError",
    "TTSError",
    "TTSQuotaExceededError",
    "ImageGenerationError",
    "VideoGenerationError",
    "VideoCompositionError",
    "FFmpegError",
    "MusicGenerationError",
    "ThumbnailError",
    "YouTubeAPIError",
    "YouTubeQuotaExceededError",
    "YouTubeAuthError",
    "YouTubeUploadError",
    "ScriptValidationError",
    "AssetNotFoundError",
    # Interfaces
    "ScriptGenerator",
    "TTSEngine",
    "ImageGenerator",
    "VideoGenerator",
    "VideoComposer",
    "ThumbnailGenerator",
    "YouTubeUploader",
    "ContentPipeline",
    # Models
    "ChannelType",
    "ContentStatus",
    "VideoStyle",
    "Script",
    "AudioSegment",
    "VisualAsset",
    "Thumbnail",
    "VideoProject",
    "ChannelConfig",
    "CHANNEL_CONFIGS",
    # Orchestrator
    "Orchestrator",
]
